services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://USER:PASSWORD@db/climbapp
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app

  db:
    image: postgres:14.12-alpine
    environment:
      - POSTGRES_DB=climbapp
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
